### ISSUE TITLE
Add world news ticker

### ISSUE THREAD

**Issue by lordkekz** [Astrothewhiteshadow/astrothewhiteshadow.github.io#3]
This is a very good website. But you know how to make it better? Give us some news.

I heard about a very cruel deed by a 96-year-old senior, why don't you have an article about it?
I was looking for an HTML tag tier list, but I can't seem to find it on your website.
Users might also want to know what you had for breakfast (at some point in the past, maybe a few years ago?) as it severely impacts their personal lives.

Thank you for improving the user experience!

**Comment by nalsai** [comment]
> Users might also want to know what you had for breakfast (at some point in the past, maybe a few years ago?) as it severely impacts their personal lives.

This is actually true and should be fixed immediately right now.

**Comment by Astrothewhiteshadow** [comment]
World News Ticker was added
