### ISSUE TITLE
Add collection for cocktails and longdrinks

### ISSUE THREAD

**Issue by lordkekz** [Astrothewhiteshadow/astrothewhiteshadow.github.io#4]
I sometimes daydream about being a little dictator, but it doesn't quite feel real. Can you help me with that?

You should showcase how to make some :b:ased cocktails and longdrinks, and maybe even some of your favorite foods as well.

Oh, and I think it'd be very fun indeed if you also added some highly toxic drinks, just to add that extra little bit of danger... **:sparkles:  no risk, no fun :sparkles:**

**Comment by Astrothewhiteshadow** [comment]
7ec3f76ba22dc2dc4f2ad3aa3f25c7db7ab3463f Recipes und der kleine Diktator wurden hinzugefügt weitere Rezepte kommen bald... <br>
